### ISSUE TITLE
Diseñar y crear la funcionalidad de Chat

### ISSUE THREAD

**Issue by tomgalbar** [Pingu-Developers/InnosoftApp#24]
Como funcionalidad añadida de la propia aplicación móvil, se implementará un chat que permita crear salas, de modo que puedan comunicarse durante las jornadas de forma rápida (ponentes-asistentes).

**Comment by alesancor1** [comment]
El backend del chat está terminado en https://github.com/Pingu-Developers/InnosoftAPI/commit/2898fbc5ea81517e074e4f082a66d05a973b1c4c.

**Comment by borjar20** [comment]
Rediseño del backend para hacer uso de Websocket en https://github.com/Pingu-Developers/InnosoftAPI/commit/f313c4d1d8c84cf046cd0fafa620c8cd60cf7c07

Implementación del frontend del chat 48b85cdca189e091ce16428b475c784b074d3cc4
