### ISSUE TITLE
Introducir mensajes personalizados en la aplicación

### ISSUE THREAD

**Issue by tomgalbar** [Pingu-Developers/InnosoftApp#26]
Se deben introducir mensajes personalizados de modo que si hubiese algún error o falta de datos este todo tratado e indicado para que el usuario comprenda lo que está ocurriendo en todo momento durante el uso de la aplicación. Por ejemplo, empezar por tratar la vista de ponentes cuando no hay datos...

**Comment by carlosatyca** [comment]
Resuelta en 0c70d8d
