### ISSUE TITLE
Testear la sección de Programa

### ISSUE THREAD

**Issue by lucasperezweb** [Pingu-Developers/InnosoftApp#43]
Se debe testear la sección de la APP "Programa" y el calendario que contiene, así como verificar su comportamiento en función a los datos que obtenga de la API.

**Comment by lucasperezweb** [comment]
Se debe testear la sección de la APP "Programa" y el calendario que contiene, así como verificar su comportamiento en función a los datos que obtenga de la API.

**Comment by carlosatyca** [comment]
Resuelto en 40198fc
